spring.application.name=mvp

# Configuración de Conexión a PostgreSQL (Docker)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mercadopublico_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# API Key / Ticket Mercado Público
mercadopublico.api.ticket=${MERCADOPUBLICO_TICKET:tu_ticket_de_prueba}

# spring.jackson.default-property-inclusion=non_null