spring.application.name=mvp

# Configuración de la Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/mercadopublico_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


# Configuración de JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update