name: Backend CI Pipeline

# 1. Cuándo se gatilla la automatización (Triggers)
on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    name: Build & Test Backend
    runs-on: ubuntu-latest # Se ejecuta en un servidor Linux virtual gratuito de GitHub

    steps:
      # Paso A: Clonar el código del repositorio en el servidor de GitHub
      - name: Checkout del código
        uses: actions/checkout@v4

      # Paso B: Configurar el entorno Java 21 (Temurin)
      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven # Guarda en caché las librerías para que futuros builds sean más rápidos

      # Paso C: Dar permisos de ejecución al ejecutable de Maven
      - name: Permisos para Maven Wrapper
        run: chmod +x mvnw

      # Paso D: Compilar el proyecto y ejecutar pruebas
      - name: Compilar y Testear con Maven
        run: ./mvnw clean package -DskipTests

      # Paso E: Validar que el Dockerfile Multi-stage compila correctamente en la nube
      - name: Validar Build de Docker
        run: docker build -t mvp-backend:ci .